use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let lib_dir = manifest_dir.join("../../lib").canonicalize().unwrap();
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed={}", lib_dir.display());

    // Discover all projects under lib/. Each subdirectory with an
    // koja.toml is a stdlib project. Its code namespace comes from
    // the manifest's `namespace = "..."` override when present,
    // otherwise it is derived from the lowercase `name = "..."`
    // (`global` -> `Global`, while `http` declares `HTTP`). The
    // auto-imported package is `Global`.
    let mut global_entries: Vec<(String, String)> = Vec::new();
    let mut qualified: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();

    let mut dirs: Vec<_> = fs::read_dir(&lib_dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", lib_dir.display()))
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().map(|ft| ft.is_dir()).unwrap_or(false))
        .collect();
    dirs.sort_by_key(|d| d.file_name());

    let mut consts = Vec::new(); // (const_name, absolute_path)
    let mut const_idx = 0usize;

    for entry in &dirs {
        let project_dir = entry.path();
        let toml_path = project_dir.join("koja.toml");
        if !toml_path.exists() {
            continue;
        }

        let src_dir = project_dir.join("src");
        if !src_dir.exists() {
            continue;
        }

        println!("cargo:rerun-if-changed={}", toml_path.display());
        let package_name = read_package_namespace(&toml_path).unwrap_or_else(|| {
            panic!(
                "missing or unparsable `name = \"...\"` in {}",
                toml_path.display()
            )
        });

        let files = discover_koja_files(&src_dir);

        for file_path in files {
            println!("cargo:rerun-if-changed={}", file_path.display());

            let stem = file_path.file_stem().unwrap().to_string_lossy().to_string();
            let module_name = if stem == package_name {
                package_name.clone()
            } else {
                format!("{package_name}.{stem}")
            };

            let const_name = format!("SRC_{const_idx}");
            consts.push((const_name.clone(), file_path.display().to_string()));

            if package_name == "Global" {
                global_entries.push((module_name, const_name));
            } else {
                qualified
                    .entry(package_name.clone())
                    .or_default()
                    .push((module_name, const_name));
            }

            const_idx += 1;
        }
    }

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs -- do not edit.\n\n");

    for (const_name, abs_path) in &consts {
        code.push_str(&format!(
            "const {const_name}: &str = include_str!(\"{abs_path}\");\n",
        ));
    }

    // Curated subset auto-imported by every pipeline run. Files
    // outside this list are still embedded as `SRC_*` constants and
    // reachable via `QUALIFIED`. New entries are added here as each
    // file becomes pipeline-ready (typecheck + lower + emit on both
    // backends).
    let autoimport_modules: &[&str] = &[
        "Global.base",
        "Global.bitwise",
        "Global.cptr",
        "Global.cstring",
        "Global.debug",
        "Global.debug_containers",
        "Global.fd",
        "Global.io",
        "Global.kernel",
        "Global.list",
        "Global.map",
        "Global.numeric",
        "Global.option",
        "Global.path",
        "Global.process",
        "Global.random",
        "Global.result",
        "Global.runtime_block",
        "Global.set",
        "Global.string",
        "Global.system",
        "Global.time",
        "Global.uri",
    ];
    code.push_str("\n/// Curated stdlib sources auto-imported by\n");
    code.push_str("/// every pipeline run (driver, tests, REPL).\n");
    code.push_str("pub const AUTOIMPORT: &[(&str, &str)] = &[\n");
    for module in autoimport_modules {
        let const_name = global_entries
            .iter()
            .find(|(name, _)| name == module)
            .map(|(_, c)| c.as_str())
            .unwrap_or_else(|| {
                panic!("AUTOIMPORT module `{module}` not found in discovered Global sources")
            });
        code.push_str(&format!("    (\"{module}\", {const_name}),\n"));
    }
    code.push_str("];\n");

    // Curated set of qualified packages user programs can `alias`
    // into scope. Pragmatic stand-in for incremental package
    // loading: each entry's full file roster is loaded eagerly so
    // `lift_signatures` / `resolve` see its types when validating a
    // user's `alias` decl. Retires once `IRPackage` caching +
    // on-demand package loads land.
    let qualified_packages: &[&str] = &["Crypto", "HTTP", "JSON", "Koja", "Net"];
    code.push_str("\n/// Stdlib sources for qualified packages user\n");
    code.push_str("/// programs can `alias` into scope. Loaded eagerly\n");
    code.push_str("/// alongside `AUTOIMPORT` as a pragmatic stand-in for\n");
    code.push_str("/// on-demand `IRPackage` loading.\n");
    code.push_str("pub const QUALIFIED: &[(&str, &str)] = &[\n");
    for package in qualified_packages {
        let entries = qualified.get(*package).unwrap_or_else(|| {
            panic!("QUALIFIED package `{package}` not found in discovered qualified sources")
        });
        for (module_name, const_name) in entries {
            code.push_str(&format!("    (\"{module_name}\", {const_name}),\n"));
        }
    }
    code.push_str("];\n");

    // Toolchain tasks exported by the `koja` package's manifest, so
    // `lib/koja/koja.toml` stays the single source of truth for what
    // the driver offers as built-in tasks (`koja new` == `koja.new`).
    let koja_toml = fs::read_to_string(lib_dir.join("koja/koja.toml")).unwrap();
    code.push_str("\n/// Tasks exported by the toolchain's `Koja` package,\n");
    code.push_str("/// parsed from the `[tasks]` table in lib/koja/koja.toml.\n");
    code.push_str("pub const TOOLCHAIN_TASKS: &[(&str, &str)] = &[\n");
    for (task_name, type_name) in read_tasks(&koja_toml) {
        code.push_str(&format!("    (\"{task_name}\", \"{type_name}\"),\n"));
    }
    code.push_str("];\n");

    fs::write(out_dir.join("stdlib_gen.rs"), code).unwrap();
}

/// Recursively discovers `.koja` files under `dir`, sorted alphabetically.
fn discover_koja_files(dir: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    collect_koja_files(dir, &mut files);
    files.sort();
    files
}

fn collect_koja_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    let mut entries: Vec<_> = entries.filter_map(|e| e.ok()).collect();
    entries.sort_by_key(|e| e.file_name());

    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            collect_koja_files(&path, out);
        } else if path.extension().map(|e| e == "koja").unwrap_or(false) {
            out.push(path.canonicalize().unwrap_or(path));
        }
    }
}

/// Extracts a package's code namespace from a project-style koja.toml,
/// preferring an explicit `namespace = "..."` over the form derived
/// from `name = "..."`. Tolerant of arbitrary whitespace and key
/// ordering, but expects double-quoted single-line values, which
/// matches every shipped koja.toml in this workspace.
fn read_package_namespace(toml_path: &Path) -> Option<String> {
    let content = fs::read_to_string(toml_path).ok()?;
    if let Some(namespace) = read_string_key(&content, "namespace") {
        return Some(namespace);
    }
    read_string_key(&content, "name").map(|name| derive_namespace(&name))
}

fn read_string_key(content: &str, key: &str) -> Option<String> {
    for line in content.lines() {
        let Some(rest) = line.trim().strip_prefix(key) else {
            continue;
        };
        let rest = rest.trim_start();
        let Some(rest) = rest.strip_prefix('=') else {
            continue;
        };
        let rest = rest.trim_start();
        let Some(rest) = rest.strip_prefix('"') else {
            continue;
        };
        let Some(end) = rest.find('"') else { continue };
        return Some(rest[..end].to_string());
    }
    None
}

/// Parses the `[tasks]` table: `"task.name" = "TypeName"` entries
/// between the `[tasks]` header and the next section header.
fn read_tasks(content: &str) -> Vec<(String, String)> {
    let mut tasks = Vec::new();
    let mut in_tasks = false;
    for line in content.lines() {
        let line = line.trim();
        if line.starts_with('[') {
            in_tasks = line == "[tasks]";
            continue;
        }
        if !in_tasks {
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let key = key.trim().trim_matches('"');
        let value = value.trim().trim_matches('"');
        if !key.is_empty() && !value.is_empty() {
            tasks.push((key.to_string(), value.to_string()));
        }
    }
    tasks
}

/// Snake-to-Pascal namespace derivation. Build scripts can't use
/// workspace crates, so this mirrors `koja_parser::derive_namespace`.
fn derive_namespace(name: &str) -> String {
    name.split('_')
        .filter(|segment| !segment.is_empty())
        .map(|segment| {
            let mut chars = segment.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}
