use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let lib_dir = manifest_dir.join("../../lib").canonicalize().unwrap();
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed={}", lib_dir.display());

    // Discover all projects under lib/. Each subdirectory with an
    // koja.toml is a stdlib project. Its code namespace comes from
    // the manifest's `namespace = "..."` override when present,
    // otherwise it is derived from the lowercase `name = "..."`
    // (`global` -> `Global`, while `http` declares `HTTP`). The
    // auto-imported package is `Global`.
    let mut global_entries: Vec<(String, String)> = Vec::new();
    let mut qualified: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();

    let mut dirs: Vec<_> = fs::read_dir(&lib_dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", lib_dir.display()))
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().map(|ft| ft.is_dir()).unwrap_or(false))
        .collect();
    dirs.sort_by_key(|d| d.file_name());

    let mut consts = Vec::new(); // (const_name, absolute_path, lib-relative path)
    let mut const_idx = 0usize;
    let mut relative_by_const: BTreeMap<String, String> = BTreeMap::new();

    for entry in &dirs {
        let project_dir = entry.path();
        let toml_path = project_dir.join("koja.toml");
        if !toml_path.exists() {
            continue;
        }

        let src_dir = project_dir.join("src");
        if !src_dir.exists() {
            continue;
        }

        println!("cargo:rerun-if-changed={}", toml_path.display());
        let package_name = read_package_namespace(&toml_path).unwrap_or_else(|| {
            panic!(
                "missing or unparsable `name = \"...\"` in {}",
                toml_path.display()
            )
        });

        let toml_const = format!("SRC_{const_idx}");
        consts.push((
            toml_const,
            toml_path.display().to_string(),
            lib_relative(&lib_dir, &toml_path),
        ));
        const_idx += 1;

        let files = discover_koja_files(&src_dir);

        for file_path in files {
            println!("cargo:rerun-if-changed={}", file_path.display());

            let stem = file_path.file_stem().unwrap().to_string_lossy().to_string();
            let module_name = if stem == package_name {
                package_name.clone()
            } else {
                format!("{package_name}.{stem}")
            };

            let const_name = format!("SRC_{const_idx}");
            let relative = lib_relative(&lib_dir, &file_path);
            relative_by_const.insert(const_name.clone(), relative.clone());
            consts.push((
                const_name.clone(),
                file_path.display().to_string(),
                relative,
            ));

            if package_name == "Global" {
                global_entries.push((module_name, const_name));
            } else {
                qualified
                    .entry(package_name.clone())
                    .or_default()
                    .push((module_name, const_name));
            }

            const_idx += 1;
        }
    }

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs -- do not edit.\n\n");

    for (const_name, abs_path, _) in &consts {
        code.push_str(&format!(
            "const {const_name}: &str = include_str!(\"{abs_path}\");\n",
        ));
    }

    // Content digest keying the on-disk extraction directory.
    let mut hash: u64 = 0xcbf29ce484222325;
    for (_, abs_path, relative) in &consts {
        fnv1a(relative.as_bytes(), &mut hash);
        fnv1a(&[0], &mut hash);
        fnv1a(&fs::read(abs_path).unwrap(), &mut hash);
        fnv1a(&[0], &mut hash);
    }
    code.push_str("\n/// First 8 hex digits of the digest of all embedded files.\n");
    code.push_str(&format!(
        "pub const STDLIB_HASH8: &str = \"{}\";\n",
        &format!("{hash:016x}")[..8]
    ));

    code.push_str("\n/// Extraction manifest: (lib-relative path, contents).\n");
    code.push_str("pub const FILES: &[(&str, &str)] = &[\n");
    for (const_name, _, relative) in &consts {
        code.push_str(&format!("    (\"{relative}\", {const_name}),\n"));
    }
    code.push_str("];\n");

    code.push_str("\n/// The full `Global` package, auto-imported by every pipeline\n");
    code.push_str("/// run, as (module, contents, lib-relative path).\n");
    code.push_str("pub const AUTOIMPORT: &[(&str, &str, &str)] = &[\n");
    for (module, const_name) in &global_entries {
        let relative = &relative_by_const[const_name];
        code.push_str(&format!(
            "    (\"{module}\", {const_name}, \"{relative}\"),\n"
        ));
    }
    code.push_str("];\n");

    code.push_str("\n/// Qualified packages user programs can `alias` into scope,\n");
    code.push_str("/// as (module, contents, lib-relative path). Loaded eagerly as\n");
    code.push_str("/// a pragmatic stand-in for on-demand `IRPackage` loading.\n");
    code.push_str("pub const QUALIFIED: &[(&str, &str, &str)] = &[\n");
    for entries in qualified.values() {
        for (module_name, const_name) in entries {
            let relative = &relative_by_const[const_name];
            code.push_str(&format!(
                "    (\"{module_name}\", {const_name}, \"{relative}\"),\n"
            ));
        }
    }
    code.push_str("];\n");

    // Toolchain tasks exported by the `koja` package's manifest, so
    // `lib/koja/koja.toml` stays the single source of truth for what
    // the driver offers as built-in tasks (`koja new` == `koja.new`).
    let koja_toml = fs::read_to_string(lib_dir.join("koja/koja.toml")).unwrap();
    code.push_str("\n/// Tasks exported by the toolchain's `Koja` package,\n");
    code.push_str("/// parsed from the `[tasks]` table in lib/koja/koja.toml.\n");
    code.push_str("pub const TOOLCHAIN_TASKS: &[(&str, &str)] = &[\n");
    for (task_name, type_name) in read_tasks(&koja_toml) {
        code.push_str(&format!("    (\"{task_name}\", \"{type_name}\"),\n"));
    }
    code.push_str("];\n");

    fs::write(out_dir.join("stdlib_gen.rs"), code).unwrap();
}

/// Path of `file` relative to `lib_dir`, with `/` separators.
fn lib_relative(lib_dir: &Path, file: &Path) -> String {
    file.strip_prefix(lib_dir)
        .unwrap_or_else(|_| panic!("{} is not under {}", file.display(), lib_dir.display()))
        .components()
        .map(|c| c.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}

/// One FNV-1a 64 step per byte, accumulated into `hash`.
fn fnv1a(bytes: &[u8], hash: &mut u64) {
    for byte in bytes {
        *hash ^= u64::from(*byte);
        *hash = hash.wrapping_mul(0x100000001b3);
    }
}

/// Recursively discovers `.koja` files under `dir`, sorted alphabetically.
fn discover_koja_files(dir: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    collect_koja_files(dir, &mut files);
    files.sort();
    files
}

fn collect_koja_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    let mut entries: Vec<_> = entries.filter_map(|e| e.ok()).collect();
    entries.sort_by_key(|e| e.file_name());

    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            collect_koja_files(&path, out);
        } else if path.extension().map(|e| e == "koja").unwrap_or(false) {
            out.push(path.canonicalize().unwrap_or(path));
        }
    }
}

/// Extracts a package's code namespace from a project-style koja.toml,
/// preferring an explicit `namespace = "..."` over the form derived
/// from `name = "..."`. Tolerant of arbitrary whitespace and key
/// ordering, but expects double-quoted single-line values, which
/// matches every shipped koja.toml in this workspace.
fn read_package_namespace(toml_path: &Path) -> Option<String> {
    let content = fs::read_to_string(toml_path).ok()?;
    if let Some(namespace) = read_string_key(&content, "namespace") {
        return Some(namespace);
    }
    read_string_key(&content, "name").map(|name| derive_namespace(&name))
}

fn read_string_key(content: &str, key: &str) -> Option<String> {
    for line in content.lines() {
        let Some(rest) = line.trim().strip_prefix(key) else {
            continue;
        };
        let rest = rest.trim_start();
        let Some(rest) = rest.strip_prefix('=') else {
            continue;
        };
        let rest = rest.trim_start();
        let Some(rest) = rest.strip_prefix('"') else {
            continue;
        };
        let Some(end) = rest.find('"') else { continue };
        return Some(rest[..end].to_string());
    }
    None
}

/// Parses the `[tasks]` table: `"task.name" = "TypeName"` entries
/// between the `[tasks]` header and the next section header.
fn read_tasks(content: &str) -> Vec<(String, String)> {
    let mut tasks = Vec::new();
    let mut in_tasks = false;
    for line in content.lines() {
        let line = line.trim();
        if line.starts_with('[') {
            in_tasks = line == "[tasks]";
            continue;
        }
        if !in_tasks {
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let key = key.trim().trim_matches('"');
        let value = value.trim().trim_matches('"');
        if !key.is_empty() && !value.is_empty() {
            tasks.push((key.to_string(), value.to_string()));
        }
    }
    tasks
}

/// Snake-to-Pascal namespace derivation. Build scripts can't use
/// workspace crates, so this mirrors `koja_parser::derive_namespace`.
fn derive_namespace(name: &str) -> String {
    name.split('_')
        .filter(|segment| !segment.is_empty())
        .map(|segment| {
            let mut chars = segment.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}
