[project]
authors = ["The Koja Authors"]
bin = "shortener"
description = "A URL shortener service backed by PostgreSQL"
entry = "App"
koja = "0.20"
license = "MIT"
name = "shortener"
version = "0.1.0"

[dependencies]
pooler = { path = "../pooler" }
postgres = { github = "hpopp/postgres-koja", tag = "v0.5.0" }
