use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let lib_dir = manifest_dir.join("../../lib").canonicalize().unwrap();
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed={}", lib_dir.display());

    // Discover all projects under lib/. Each subdirectory with an expo.toml
    // is a stdlib project. The directory name is the package name.
    let mut std_entries: Vec<(String, String)> = Vec::new(); // (module_name, const_name)
    let mut qualified: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();

    let mut dirs: Vec<_> = fs::read_dir(&lib_dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", lib_dir.display()))
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().map(|ft| ft.is_dir()).unwrap_or(false))
        .collect();
    dirs.sort_by_key(|d| d.file_name());

    let mut consts = Vec::new(); // (const_name, absolute_path)
    let mut const_idx = 0usize;

    for entry in &dirs {
        let dir_name = entry.file_name().to_string_lossy().to_string();
        let project_dir = entry.path();

        if !project_dir.join("expo.toml").exists() {
            continue;
        }

        let src_dir = project_dir.join("src");
        if !src_dir.exists() {
            continue;
        }

        let files = discover_expo_files(&src_dir);

        for file_path in files {
            println!("cargo:rerun-if-changed={}", file_path.display());

            let stem = file_path.file_stem().unwrap().to_string_lossy().to_string();
            let module_name = if stem == dir_name {
                dir_name.clone()
            } else {
                format!("{dir_name}.{stem}")
            };

            let const_name = format!("SRC_{const_idx}");
            consts.push((const_name.clone(), file_path.display().to_string()));

            if dir_name == "std" {
                std_entries.push((module_name, const_name));
            } else {
                qualified
                    .entry(dir_name.clone())
                    .or_default()
                    .push((module_name, const_name));
            }

            const_idx += 1;
        }
    }

    // Generate stdlib_gen.rs
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs -- do not edit.\n\n");

    for (const_name, abs_path) in &consts {
        code.push_str(&format!(
            "const {const_name}: &str = include_str!(\"{abs_path}\");\n",
        ));
    }

    code.push_str("\n/// All stdlib sources. `std` modules first (auto-imported),\n");
    code.push_str("/// then qualified packages in alphabetical order.\n");
    code.push_str("pub const SOURCES: &[(&str, &str)] = &[\n");

    for (module_name, const_name) in &std_entries {
        code.push_str(&format!("    (\"{module_name}\", {const_name}),\n"));
    }
    for files in qualified.values() {
        for (module_name, const_name) in files {
            code.push_str(&format!("    (\"{module_name}\", {const_name}),\n"));
        }
    }
    code.push_str("];\n");

    code.push_str("\n/// Package names that require qualified access.\n");
    code.push_str("pub const QUALIFIED_MODULES: &[&str] = &[\n");
    for pkg in qualified.keys() {
        code.push_str(&format!("    \"{pkg}\",\n"));
    }
    code.push_str("];\n");

    fs::write(out_dir.join("stdlib_gen.rs"), code).unwrap();
}

/// Recursively discovers `.expo` files under `dir`, sorted alphabetically.
fn discover_expo_files(dir: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    collect_expo_files(dir, &mut files);
    files.sort();
    files
}

fn collect_expo_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    let mut entries: Vec<_> = entries.filter_map(|e| e.ok()).collect();
    entries.sort_by_key(|e| e.file_name());

    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            collect_expo_files(&path, out);
        } else if path.extension().map(|e| e == "expo").unwrap_or(false) {
            out.push(path.canonicalize().unwrap_or(path));
        }
    }
}
