use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let lib_dir = manifest_dir.join("../../lib").canonicalize().unwrap();
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed={}", lib_dir.display());

    // Discover all projects under lib/. Each subdirectory with an expo.toml is
    // a stdlib project. Its package name comes from the `name = "..."` field
    // in expo.toml (Elixir-style: directory is snake_case, package is
    // PascalCase, the auto-imported package is `Global`).
    // (module_name, const_name, alpha_only)
    let mut global_entries: Vec<(String, String, bool)> = Vec::new();
    let mut qualified: BTreeMap<String, Vec<(String, String, bool)>> = BTreeMap::new();

    let mut dirs: Vec<_> = fs::read_dir(&lib_dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", lib_dir.display()))
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().map(|ft| ft.is_dir()).unwrap_or(false))
        .collect();
    dirs.sort_by_key(|d| d.file_name());

    // Files whose stem starts with `alpha_` are auto-generated /
    // alpha-pipeline-only (e.g. hand-written Debug impls for stdlib
    // generic containers). They land in `ALPHA_AUTOIMPORT` and the
    // master `SRC_*` constant table, but never in `SOURCES` —
    // which is the v1 path's source list and lacks the
    // universal-Debug fallback the alpha pipeline relies on.
    let mut consts = Vec::new(); // (const_name, absolute_path)
    let mut const_idx = 0usize;

    for entry in &dirs {
        let project_dir = entry.path();
        let toml_path = project_dir.join("expo.toml");
        if !toml_path.exists() {
            continue;
        }

        let src_dir = project_dir.join("src");
        if !src_dir.exists() {
            continue;
        }

        println!("cargo:rerun-if-changed={}", toml_path.display());
        let package_name = read_package_name(&toml_path).unwrap_or_else(|| {
            panic!(
                "missing or unparsable `name = \"...\"` in {}",
                toml_path.display()
            )
        });

        let files = discover_expo_files(&src_dir);

        for file_path in files {
            println!("cargo:rerun-if-changed={}", file_path.display());

            let stem = file_path.file_stem().unwrap().to_string_lossy().to_string();
            let module_name = if stem == package_name {
                package_name.clone()
            } else {
                format!("{package_name}.{stem}")
            };

            let const_name = format!("SRC_{const_idx}");
            consts.push((const_name.clone(), file_path.display().to_string()));
            let alpha_only = stem.starts_with("alpha_");

            if package_name == "Global" {
                global_entries.push((module_name, const_name, alpha_only));
            } else {
                qualified.entry(package_name.clone()).or_default().push((
                    module_name,
                    const_name,
                    alpha_only,
                ));
            }

            const_idx += 1;
        }
    }

    // Generate stdlib_gen.rs
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs -- do not edit.\n\n");

    for (const_name, abs_path) in &consts {
        code.push_str(&format!(
            "const {const_name}: &str = include_str!(\"{abs_path}\");\n",
        ));
    }

    code.push_str("\n/// All stdlib sources. `Global` modules first (auto-imported),\n");
    code.push_str("/// then qualified packages in alphabetical order.\n");
    code.push_str("pub const SOURCES: &[(&str, &str)] = &[\n");

    for (module_name, const_name, alpha_only) in &global_entries {
        if *alpha_only {
            continue;
        }
        code.push_str(&format!("    (\"{module_name}\", {const_name}),\n"));
    }
    for files in qualified.values() {
        for (module_name, const_name, alpha_only) in files {
            if *alpha_only {
                continue;
            }
            code.push_str(&format!("    (\"{module_name}\", {const_name}),\n"));
        }
    }
    code.push_str("];\n");

    code.push_str("\n/// Package names that require qualified access.\n");
    code.push_str("pub const QUALIFIED_MODULES: &[&str] = &[\n");
    for pkg in qualified.keys() {
        code.push_str(&format!("    \"{pkg}\",\n"));
    }
    code.push_str("];\n");

    // Curated subset auto-imported by the alpha pipeline. Files outside this
    // list are still embedded in `SOURCES` for the v1 path; only the alpha
    // pipeline reads `ALPHA_AUTOIMPORT`. Entries are added here as each file
    // becomes alpha-ready (typecheck + lower + emit on both backends).
    let alpha_modules: &[&str] = &[
        // kernel first — defines Option/Result/Pair referenced downstream
        "Global.kernel",
        "Global.cptr",
        "Global.cstring",
        "Global.bitwise",
        "Global.fd",
        "Global.io",
        "Global.list",
        "Global.map",
        "Global.set",
        "Global.string",
        // debug after string (uses `String.escape_debug` in `Debug for
        // String`) and io (`Debug.print` calls `IO.puts`).
        "Global.debug",
        // alpha_debug_containers ships hand-written `Debug` impls for
        // the stdlib generic containers (Pair / Option / Result /
        // List / Map / Set). Lives in an `alpha_*.expo` file so the
        // v1 path doesn't see it (v1's synthesizer produces no-op
        // Debug bodies for generics; the alpha pipeline's
        // universal-Debug fallback makes proper bodies legal). Must
        // come after `Global.debug` and `Global.list` etc. so the
        // protocol decl + container types are already in scope.
        "Global.alpha_debug_containers",
        "Global.system",
        "Global.time",
        // process needs `Task<R>.run`'s `self.work()` to typecheck via
        // alpha-typecheck's field-as-callable dispatch (a struct's
        // function-typed field called with method syntax desugars to
        // `(self.field)(args)`). Order: after the leaf containers but
        // before random, which has no dependency either way.
        "Global.process",
        // random comes last — calls into `String.to_binary`, so the string
        // module must be lowered before this module's bodies can resolve.
        "Global.random",
    ];
    code.push_str("\n/// Stdlib sources auto-imported by the alpha pipeline.\n");
    code.push_str("/// Subset of `SOURCES`; grows as files become alpha-ready.\n");
    code.push_str("pub const ALPHA_AUTOIMPORT: &[(&str, &str)] = &[\n");
    for module in alpha_modules {
        let const_name = global_entries
            .iter()
            .find(|(name, _, _)| name == module)
            .map(|(_, c, _)| c.as_str())
            .unwrap_or_else(|| {
                panic!("ALPHA_AUTOIMPORT module `{module}` not found in discovered Global sources")
            });
        code.push_str(&format!("    (\"{module}\", {const_name}),\n"));
    }
    code.push_str("];\n");

    fs::write(out_dir.join("stdlib_gen.rs"), code).unwrap();
}

/// Recursively discovers `.expo` files under `dir`, sorted alphabetically.
fn discover_expo_files(dir: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    collect_expo_files(dir, &mut files);
    files.sort();
    files
}

fn collect_expo_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    let mut entries: Vec<_> = entries.filter_map(|e| e.ok()).collect();
    entries.sort_by_key(|e| e.file_name());

    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            collect_expo_files(&path, out);
        } else if path.extension().map(|e| e == "expo").unwrap_or(false) {
            out.push(path.canonicalize().unwrap_or(path));
        }
    }
}

/// Extracts the `name = "..."` value from a project-style expo.toml. Tolerant
/// of arbitrary whitespace and key ordering, but expects the value to be a
/// double-quoted string on a single line, which matches every shipped
/// expo.toml in this workspace.
fn read_package_name(toml_path: &Path) -> Option<String> {
    let content = fs::read_to_string(toml_path).ok()?;
    for line in content.lines() {
        let Some(rest) = line.trim().strip_prefix("name") else {
            continue;
        };
        let rest = rest.trim_start();
        let Some(rest) = rest.strip_prefix('=') else {
            continue;
        };
        let rest = rest.trim_start();
        let Some(rest) = rest.strip_prefix('"') else {
            continue;
        };
        let Some(end) = rest.find('"') else { continue };
        return Some(rest[..end].to_string());
    }
    None
}
